//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("View.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private.
        /// </summary>
        public static string _private {
            get {
                return ResourceManager.GetString("private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Public.
        /// </summary>
        public static string _public {
            get {
                return ResourceManager.GetString("public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept setting.
        /// </summary>
        public static string accept_setting {
            get {
                return ResourceManager.GetString("accept_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string add_Friend {
            get {
                return ResourceManager.GetString("add_Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a amount of money bet.
        /// </summary>
        public static string amount_of_money_bet {
            get {
                return ResourceManager.GetString("amount_of_money_bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bet amount.
        /// </summary>
        public static string bet_amount {
            get {
                return ResourceManager.GetString("bet_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Black.
        /// </summary>
        public static string black {
            get {
                return ResourceManager.GetString("black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brown.
        /// </summary>
        public static string brown {
            get {
                return ResourceManager.GetString("brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title lobby.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change bean color.
        /// </summary>
        public static string change_bean_color {
            get {
                return ResourceManager.GetString("change_bean_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a change card border.
        /// </summary>
        public static string change_card_border {
            get {
                return ResourceManager.GetString("change_card_border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check the code.
        /// </summary>
        public static string check_the_code {
            get {
                return ResourceManager.GetString("check_the_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check your email or spam folder.
        /// </summary>
        public static string check_your_email {
            get {
                return ResourceManager.GetString("check_your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create game.
        /// </summary>
        public static string create_game {
            get {
                return ResourceManager.GetString("create_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of birth.
        /// </summary>
        public static string date_of_birth {
            get {
                return ResourceManager.GetString("date_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter new password.
        /// </summary>
        public static string enter_new_password {
            get {
                return ResourceManager.GetString("enter_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter password.
        /// </summary>
        public static string enter_password {
            get {
                return ResourceManager.GetString("enter_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the code.
        /// </summary>
        public static string enter_the_code {
            get {
                return ResourceManager.GetString("enter_the_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fast.
        /// </summary>
        public static string fast {
            get {
                return ResourceManager.GetString("fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forget the password?.
        /// </summary>
        public static string forget_the_password {
            get {
                return ResourceManager.GetString("forget_the_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend.
        /// </summary>
        public static string friend {
            get {
                return ResourceManager.GetString("friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend list.
        /// </summary>
        public static string friend_list {
            get {
                return ResourceManager.GetString("friend_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game type.
        /// </summary>
        public static string game_type {
            get {
                return ResourceManager.GetString("game_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idiom.
        /// </summary>
        public static string idiom {
            get {
                return ResourceManager.GetString("idiom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join a game.
        /// </summary>
        public static string join_a_game {
            get {
                return ResourceManager.GetString("join_a_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log out.
        /// </summary>
        public static string log_out {
            get {
                return ResourceManager.GetString("log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of players.
        /// </summary>
        public static string number_of_players {
            get {
                return ResourceManager.GetString("number_of_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orbed.
        /// </summary>
        public static string orbed {
            get {
                return ResourceManager.GetString("orbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords.
        /// </summary>
        public static string passwords {
            get {
                return ResourceManager.GetString("passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play as a guest.
        /// </summary>
        public static string play_as_a_guest {
            get {
                return ResourceManager.GetString("play_as_a_guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recent people.
        /// </summary>
        public static string recent_people {
            get {
                return ResourceManager.GetString("recent_people", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Red.
        /// </summary>
        public static string red {
            get {
                return ResourceManager.GetString("red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register user.
        /// </summary>
        public static string register_user {
            get {
                return ResourceManager.GetString("register_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a regular.
        /// </summary>
        public static string regular {
            get {
                return ResourceManager.GetString("regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        public static string remove_Friend {
            get {
                return ResourceManager.GetString("remove_Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a card.
        /// </summary>
        public static string select_a_card {
            get {
                return ResourceManager.GetString("select_a_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send verification code.
        /// </summary>
        public static string send_verification_code {
            get {
                return ResourceManager.GetString("send_verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Setting.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        public static string sign_in {
            get {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Slow.
        /// </summary>
        public static string slow {
            get {
                return ResourceManager.GetString("slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound.
        /// </summary>
        public static string sound {
            get {
                return ResourceManager.GetString("sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound of voices.
        /// </summary>
        public static string sound_of_voices {
            get {
                return ResourceManager.GetString("sound_of_voices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string spanish {
            get {
                return ResourceManager.GetString("spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Speed game.
        /// </summary>
        public static string speed_game {
            get {
                return ResourceManager.GetString("speed_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Square.
        /// </summary>
        public static string square {
            get {
                return ResourceManager.GetString("square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start game.
        /// </summary>
        public static string start_game {
            get {
                return ResourceManager.GetString("start_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loteria.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email verification.
        /// </summary>
        public static string title_email_verification {
            get {
                return ResourceManager.GetString("title_email_verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify profile.
        /// </summary>
        public static string title_modify_profile {
            get {
                return ResourceManager.GetString("title_modify_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Setting game.
        /// </summary>
        public static string title_setting_game {
            get {
                return ResourceManager.GetString("title_setting_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Synchronizing.
        /// </summary>
        public static string title_synchronizing {
            get {
                return ResourceManager.GetString("title_synchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main.
        /// </summary>
        public static string titleMain {
            get {
                return ResourceManager.GetString("titleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
