//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept setting.
        /// </summary>
        public static string AcceptSetting {
            get {
                return ResourceManager.GetString("AcceptSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string AddFriend {
            get {
                return ResourceManager.GetString("AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a amount of money bet.
        /// </summary>
        public static string AmountOfMoneyBet {
            get {
                return ResourceManager.GetString("AmountOfMoneyBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bet amount.
        /// </summary>
        public static string BetAmount {
            get {
                return ResourceManager.GetString("BetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brown.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change bean color.
        /// </summary>
        public static string ChangeBeanColor {
            get {
                return ResourceManager.GetString("ChangeBeanColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a change card border.
        /// </summary>
        public static string ChangeCardBorder {
            get {
                return ResourceManager.GetString("ChangeCardBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check the code.
        /// </summary>
        public static string CheckTheCode {
            get {
                return ResourceManager.GetString("CheckTheCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check your email or spam folder.
        /// </summary>
        public static string CheckYourEmail {
            get {
                return ResourceManager.GetString("CheckYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create game.
        /// </summary>
        public static string CreateGame {
            get {
                return ResourceManager.GetString("CreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter new password.
        /// </summary>
        public static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the code.
        /// </summary>
        public static string EnterTheCode {
            get {
                return ResourceManager.GetString("EnterTheCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fast.
        /// </summary>
        public static string Fast {
            get {
                return ResourceManager.GetString("Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forget the password?.
        /// </summary>
        public static string ForgetThePassword {
            get {
                return ResourceManager.GetString("ForgetThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend.
        /// </summary>
        public static string Friend {
            get {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend list.
        /// </summary>
        public static string FriendList {
            get {
                return ResourceManager.GetString("FriendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game Loteria.
        /// </summary>
        public static string GameLoteria {
            get {
                return ResourceManager.GetString("GameLoteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game type.
        /// </summary>
        public static string GameType {
            get {
                return ResourceManager.GetString("GameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idiom.
        /// </summary>
        public static string Idiom {
            get {
                return ResourceManager.GetString("Idiom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join a game.
        /// </summary>
        public static string JoinAGame {
            get {
                return ResourceManager.GetString("JoinAGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of players.
        /// </summary>
        public static string NumberOfPlayers {
            get {
                return ResourceManager.GetString("NumberOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orbed.
        /// </summary>
        public static string Orbed {
            get {
                return ResourceManager.GetString("Orbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password Confirm.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords.
        /// </summary>
        public static string Passwords {
            get {
                return ResourceManager.GetString("Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play as a guest.
        /// </summary>
        public static string PlayAsAGuest {
            get {
                return ResourceManager.GetString("PlayAsAGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Public.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recent people.
        /// </summary>
        public static string RecentPeople {
            get {
                return ResourceManager.GetString("RecentPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register user.
        /// </summary>
        public static string RegistersUser {
            get {
                return ResourceManager.GetString("RegistersUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a regular.
        /// </summary>
        public static string Regular {
            get {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        public static string RemoveFriend {
            get {
                return ResourceManager.GetString("RemoveFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a card.
        /// </summary>
        public static string SelectACard {
            get {
                return ResourceManager.GetString("SelectACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send verification code.
        /// </summary>
        public static string SendVerificationCode {
            get {
                return ResourceManager.GetString("SendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Slow.
        /// </summary>
        public static string Slow {
            get {
                return ResourceManager.GetString("Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound of voices.
        /// </summary>
        public static string SoundOfVoices {
            get {
                return ResourceManager.GetString("SoundOfVoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Speed game.
        /// </summary>
        public static string SpeedGame {
            get {
                return ResourceManager.GetString("SpeedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Square.
        /// </summary>
        public static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start game.
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loteria.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email verification.
        /// </summary>
        public static string TitleEmailVerification {
            get {
                return ResourceManager.GetString("TitleEmailVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main.
        /// </summary>
        public static string TitleMain {
            get {
                return ResourceManager.GetString("TitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify profile.
        /// </summary>
        public static string TitleModifyProfile {
            get {
                return ResourceManager.GetString("TitleModifyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Setting game.
        /// </summary>
        public static string TitleSettingGame {
            get {
                return ResourceManager.GetString("TitleSettingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Synchronizing.
        /// </summary>
        public static string TitleSynchronizing {
            get {
                return ResourceManager.GetString("TitleSynchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to the game.
        /// </summary>
        public static string WelcomeToTheGame {
            get {
                return ResourceManager.GetString("WelcomeToTheGame", resourceCulture);
            }
        }
    }
}
