//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("View.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string _private {
            get {
                return ResourceManager.GetString("private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string _public {
            get {
                return ResourceManager.GetString("public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Of Money.
        /// </summary>
        public static string amountOfMoney {
            get {
                return ResourceManager.GetString("amountOfMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change The Password.
        /// </summary>
        public static string changeThePassword {
            get {
                return ResourceManager.GetString("changeThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email.
        /// </summary>
        public static string checkYourEmail {
            get {
                return ResourceManager.GetString("checkYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Play.
        /// </summary>
        public static string codePlay {
            get {
                return ResourceManager.GetString("codePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Game.
        /// </summary>
        public static string configureGame {
            get {
                return ResourceManager.GetString("configureGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Perfil.
        /// </summary>
        public static string configureProfile {
            get {
                return ResourceManager.GetString("configureProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string confirmNewPassword {
            get {
                return ResourceManager.GetString("confirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct code.
        /// </summary>
        public static string correctCode {
            get {
                return ResourceManager.GetString("correctCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send email.
        /// </summary>
        public static string couldNotSendEmail {
            get {
                return ResourceManager.GetString("couldNotSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update successfully.
        /// </summary>
        public static string couldNotUpdateSuccessfully {
            get {
                return ResourceManager.GetString("couldNotUpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Game.
        /// </summary>
        public static string createGame {
            get {
                return ResourceManager.GetString("createGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string dateOfBirth {
            get {
                return ResourceManager.GetString("dateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deficient password.
        /// </summary>
        public static string deficientPassword {
            get {
                return ResourceManager.GetString("deficientPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not remove yourself.
        /// </summary>
        public static string doNotRemoveYourself {
            get {
                return ResourceManager.GetString("doNotRemoveYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Code.
        /// </summary>
        public static string enterCode {
            get {
                return ResourceManager.GetString("enterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Game Code.
        /// </summary>
        public static string enterGameCode {
            get {
                return ResourceManager.GetString("enterGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Passsword.
        /// </summary>
        public static string enterNewPassword {
            get {
                return ResourceManager.GetString("enterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter The Email.
        /// </summary>
        public static string enterTheEmail {
            get {
                return ResourceManager.GetString("enterTheEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Your Password.
        /// </summary>
        public static string forgotYourPassword {
            get {
                return ResourceManager.GetString("forgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Loteria.
        /// </summary>
        public static string gameLoteria {
            get {
                return ResourceManager.GetString("gameLoteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete date of birth.
        /// </summary>
        public static string incompleteDateOfBirth {
            get {
                return ResourceManager.GetString("incompleteDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format.
        /// </summary>
        public static string invalidFormat {
            get {
                return ResourceManager.GetString("invalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mail format.
        /// </summary>
        public static string invalidMailFormat {
            get {
                return ResourceManager.GetString("invalidMailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid nickname.
        /// </summary>
        public static string invalidNickname {
            get {
                return ResourceManager.GetString("invalidNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Game.
        /// </summary>
        public static string joinGame {
            get {
                return ResourceManager.GetString("joinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby.
        /// </summary>
        public static string lobby {
            get {
                return ResourceManager.GetString("lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loteria.
        /// </summary>
        public static string loteria {
            get {
                return ResourceManager.GetString("loteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail already registered.
        /// </summary>
        public static string mailAlreadyRegistered {
            get {
                return ResourceManager.GetString("mailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string mainMenu {
            get {
                return ResourceManager.GetString("mainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is invalid.
        /// </summary>
        public static string nameIsInvalid {
            get {
                return ResourceManager.GetString("nameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname already registered.
        /// </summary>
        public static string nicknameAlreadyRegistered {
            get {
                return ResourceManager.GetString("nicknameAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Players.
        /// </summary>
        public static string numberPlayer {
            get {
                return ResourceManager.GetString("numberPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline, please try again later.
        /// </summary>
        public static string offlinePleaseTryAgainLater {
            get {
                return ResourceManager.GetString("offlinePleaseTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string passwordsDoNotMatch {
            get {
                return ResourceManager.GetString("passwordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play As A Guest.
        /// </summary>
        public static string playAsAGuest {
            get {
                return ResourceManager.GetString("playAsAGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly.
        /// </summary>
        public static string quickly {
            get {
                return ResourceManager.GetString("quickly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectify the fields.
        /// </summary>
        public static string rectifyTheFields {
            get {
                return ResourceManager.GetString("rectifyTheFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register At.
        /// </summary>
        public static string registerAt {
            get {
                return ResourceManager.GetString("registerAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful.
        /// </summary>
        public static string registrationSuccessful {
            get {
                return ResourceManager.GetString("registrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room full.
        /// </summary>
        public static string roomFull {
            get {
                return ResourceManager.GetString("roomFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string slow {
            get {
                return ResourceManager.GetString("slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string spanish {
            get {
                return ResourceManager.GetString("spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Of The Match.
        /// </summary>
        public static string speedOfTheMatch {
            get {
                return ResourceManager.GetString("speedOfTheMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string standard {
            get {
                return ResourceManager.GetString("standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username and/or password you entered are not registered.
        /// </summary>
        public static string theUsernamePasswordYouEnteredAreNotRegistered {
            get {
                return ResourceManager.GetString("theUsernamePasswordYouEnteredAreNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email does not exist.
        /// </summary>
        public static string thisEmailDoesNotExist {
            get {
                return ResourceManager.GetString("thisEmailDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This room does not exist.
        /// </summary>
        public static string thisRoomDoesNotExist {
            get {
                return ResourceManager.GetString("thisRoomDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Item.
        /// </summary>
        public static string typeOfItem {
            get {
                return ResourceManager.GetString("typeOfItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Data.
        /// </summary>
        public static string updateData {
            get {
                return ResourceManager.GetString("updateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code does not match.
        /// </summary>
        public static string verificationCodeDoesNotMatch {
            get {
                return ResourceManager.GetString("verificationCodeDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Email.
        /// </summary>
        public static string verificationEmail {
            get {
                return ResourceManager.GetString("verificationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string welcomeTo {
            get {
                return ResourceManager.GetString("welcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are NOT registered yet, REGISTER NOW&quot;.
        /// </summary>
        public static string youAreNOTRegisteredYet {
            get {
                return ResourceManager.GetString("youAreNOTRegisteredYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot log in twice.
        /// </summary>
        public static string youCannotLogInTwice {
            get {
                return ResourceManager.GetString("youCannotLogInTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t be your own friend.
        /// </summary>
        public static string youCantBeYourOwnFriend {
            get {
                return ResourceManager.GetString("youCantBeYourOwnFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been expelled.
        /// </summary>
        public static string youHaveBeenExpelled {
            get {
                return ResourceManager.GetString("youHaveBeenExpelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully updated.
        /// </summary>
        public static string youHaveSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("youHaveSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your earned coins will not be saved.
        /// </summary>
        public static string yourEarnedCoinsWillNotBeSaved {
            get {
                return ResourceManager.GetString("yourEarnedCoinsWillNotBeSaved", resourceCulture);
            }
        }
    }
}
