//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("View.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private.
        /// </summary>
        public static string _private {
            get {
                return ResourceManager.GetString("private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Public.
        /// </summary>
        public static string _public {
            get {
                return ResourceManager.GetString("public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount Of Money.
        /// </summary>
        public static string amountOfMoney {
            get {
                return ResourceManager.GetString("amountOfMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Application rejected.
        /// </summary>
        public static string applicationRejected {
            get {
                return ResourceManager.GetString("applicationRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Application submitted.
        /// </summary>
        public static string applicationSubmitted {
            get {
                return ResourceManager.GetString("applicationSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attempts Exhausted.
        /// </summary>
        public static string attemptsExhausted {
            get {
                return ResourceManager.GetString("attemptsExhausted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change The Password.
        /// </summary>
        public static string changeThePassword {
            get {
                return ResourceManager.GetString("changeThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check your email.
        /// </summary>
        public static string checkYourEmail {
            get {
                return ResourceManager.GetString("checkYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code Play.
        /// </summary>
        public static string codePlay {
            get {
                return ResourceManager.GetString("codePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code Verification.
        /// </summary>
        public static string codeVerification {
            get {
                return ResourceManager.GetString("codeVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configure Game.
        /// </summary>
        public static string configureGame {
            get {
                return ResourceManager.GetString("configureGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar Perfil.
        /// </summary>
        public static string configureProfile {
            get {
                return ResourceManager.GetString("configureProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm New Password.
        /// </summary>
        public static string confirmNewPassword {
            get {
                return ResourceManager.GetString("confirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correct code.
        /// </summary>
        public static string correctCode {
            get {
                return ResourceManager.GetString("correctCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not send email.
        /// </summary>
        public static string couldNotSendEmail {
            get {
                return ResourceManager.GetString("couldNotSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not update successfully.
        /// </summary>
        public static string couldNotUpdateSuccessfully {
            get {
                return ResourceManager.GetString("couldNotUpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Game.
        /// </summary>
        public static string createGame {
            get {
                return ResourceManager.GetString("createGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date Of Birth.
        /// </summary>
        public static string dateOfBirth {
            get {
                return ResourceManager.GetString("dateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decline.
        /// </summary>
        public static string decline {
            get {
                return ResourceManager.GetString("decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deficient password.
        /// </summary>
        public static string deficientPassword {
            get {
                return ResourceManager.GetString("deficientPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do not remove yourself.
        /// </summary>
        public static string doNotRemoveYourself {
            get {
                return ResourceManager.GetString("doNotRemoveYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Code.
        /// </summary>
        public static string enterCode {
            get {
                return ResourceManager.GetString("enterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Game Code.
        /// </summary>
        public static string enterGameCode {
            get {
                return ResourceManager.GetString("enterGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter New Passsword.
        /// </summary>
        public static string enterNewPassword {
            get {
                return ResourceManager.GetString("enterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter The Email.
        /// </summary>
        public static string enterTheEmail {
            get {
                return ResourceManager.GetString("enterTheEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot Your Password.
        /// </summary>
        public static string forgotYourPassword {
            get {
                return ResourceManager.GetString("forgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request.
        /// </summary>
        public static string friendRequest {
            get {
                return ResourceManager.GetString("friendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friendship request from.
        /// </summary>
        public static string friendshipRequestFrom {
            get {
                return ResourceManager.GetString("friendshipRequestFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game Loteria.
        /// </summary>
        public static string gameLoteria {
            get {
                return ResourceManager.GetString("gameLoteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest.
        /// </summary>
        public static string guest {
            get {
                return ResourceManager.GetString("guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incomplete date of birth.
        /// </summary>
        public static string incompleteDateOfBirth {
            get {
                return ResourceManager.GetString("incompleteDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insufficient Coins.
        /// </summary>
        public static string insufficientCoins {
            get {
                return ResourceManager.GetString("insufficientCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid format.
        /// </summary>
        public static string invalidFormat {
            get {
                return ResourceManager.GetString("invalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid mail format.
        /// </summary>
        public static string invalidMailFormat {
            get {
                return ResourceManager.GetString("invalidMailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid nickname.
        /// </summary>
        public static string invalidNickname {
            get {
                return ResourceManager.GetString("invalidNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Game.
        /// </summary>
        public static string joinGame {
            get {
                return ResourceManager.GetString("joinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby.
        /// </summary>
        public static string lobby {
            get {
                return ResourceManager.GetString("lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loteria.
        /// </summary>
        public static string loteria {
            get {
                return ResourceManager.GetString("loteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mail already registered.
        /// </summary>
        public static string mailAlreadyRegistered {
            get {
                return ResourceManager.GetString("mailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main Menu.
        /// </summary>
        public static string mainMenu {
            get {
                return ResourceManager.GetString("mainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name is invalid.
        /// </summary>
        public static string nameIsInvalid {
            get {
                return ResourceManager.GetString("nameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname already registered.
        /// </summary>
        public static string nicknameAlreadyRegistered {
            get {
                return ResourceManager.GetString("nicknameAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of attempts exhausted.
        /// </summary>
        public static string numberOfAttemptsExhausted {
            get {
                return ResourceManager.GetString("numberOfAttemptsExhausted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of Players.
        /// </summary>
        public static string numberPlayer {
            get {
                return ResourceManager.GetString("numberPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offline, please try again later.
        /// </summary>
        public static string offlinePleaseTryAgainLater {
            get {
                return ResourceManager.GetString("offlinePleaseTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match.
        /// </summary>
        public static string passwordsDoNotMatch {
            get {
                return ResourceManager.GetString("passwordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play As A Guest.
        /// </summary>
        public static string playAsAGuest {
            get {
                return ResourceManager.GetString("playAsAGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quickly.
        /// </summary>
        public static string quickly {
            get {
                return ResourceManager.GetString("quickly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rectify the fields.
        /// </summary>
        public static string rectifyTheFields {
            get {
                return ResourceManager.GetString("rectifyTheFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register At.
        /// </summary>
        public static string registerAt {
            get {
                return ResourceManager.GetString("registerAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration successful.
        /// </summary>
        public static string registrationSuccessful {
            get {
                return ResourceManager.GetString("registrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Room full.
        /// </summary>
        public static string roomFull {
            get {
                return ResourceManager.GetString("roomFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Slow.
        /// </summary>
        public static string slow {
            get {
                return ResourceManager.GetString("slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string spanish {
            get {
                return ResourceManager.GetString("spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Speed Of The Match.
        /// </summary>
        public static string speedOfTheMatch {
            get {
                return ResourceManager.GetString("speedOfTheMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Standard.
        /// </summary>
        public static string standard {
            get {
                return ResourceManager.GetString("standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The minimum number of players is 3.
        /// </summary>
        public static string theMinimumNumberOfPlayers {
            get {
                return ResourceManager.GetString("theMinimumNumberOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username and/or password you entered are not registered.
        /// </summary>
        public static string theUsernamePasswordYouEnteredAreNotRegistered {
            get {
                return ResourceManager.GetString("theUsernamePasswordYouEnteredAreNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This email does not exist.
        /// </summary>
        public static string thisEmailDoesNotExist {
            get {
                return ResourceManager.GetString("thisEmailDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This room does not exist.
        /// </summary>
        public static string thisRoomDoesNotExist {
            get {
                return ResourceManager.GetString("thisRoomDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type Of Item.
        /// </summary>
        public static string typeOfItem {
            get {
                return ResourceManager.GetString("typeOfItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable To Perform This Action.
        /// </summary>
        public static string unableToPerformThisAction {
            get {
                return ResourceManager.GetString("unableToPerformThisAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Data.
        /// </summary>
        public static string updateData {
            get {
                return ResourceManager.GetString("updateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code does not match.
        /// </summary>
        public static string verificationCodeDoesNotMatch {
            get {
                return ResourceManager.GetString("verificationCodeDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification Email.
        /// </summary>
        public static string verificationEmail {
            get {
                return ResourceManager.GetString("verificationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We Have Winner.
        /// </summary>
        public static string weHaveWinner {
            get {
                return ResourceManager.GetString("weHaveWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        public static string welcomeTo {
            get {
                return ResourceManager.GetString("welcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a winner.
        /// </summary>
        public static string winner {
            get {
                return ResourceManager.GetString("winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are NOT registered yet, REGISTER NOW&quot;.
        /// </summary>
        public static string youAreNOTRegisteredYet {
            get {
                return ResourceManager.GetString("youAreNOTRegisteredYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot log in twice.
        /// </summary>
        public static string youCannotLogInTwice {
            get {
                return ResourceManager.GetString("youCannotLogInTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t be your own friend.
        /// </summary>
        public static string youCantBeYourOwnFriend {
            get {
                return ResourceManager.GetString("youCantBeYourOwnFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been expelled.
        /// </summary>
        public static string youHaveBeenExpelled {
            get {
                return ResourceManager.GetString("youHaveBeenExpelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have a new friend.
        /// </summary>
        public static string youHaveNewFriend {
            get {
                return ResourceManager.GetString("youHaveNewFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have successfully updated.
        /// </summary>
        public static string youHaveSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("youHaveSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your earned coins will not be saved.
        /// </summary>
        public static string yourEarnedCoinsWillNotBeSaved {
            get {
                return ResourceManager.GetString("yourEarnedCoinsWillNotBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your friends list is full.
        /// </summary>
        public static string yourFriendsListIsFull {
            get {
                return ResourceManager.GetString("yourFriendsListIsFull", resourceCulture);
            }
        }
    }
}
